using UnityEngine;

[System.Serializable]
public class SoundItem
{

    public enum SoundName
    {
        NoSound,
        TypewriterSound,
        WalkingSound,
        ChipsCrunch,
        TrainWhistle,
        TrainMoving,
        TrainStation,
        Driving,
        OpenFrontDoor,
        WalkingOnWood,
        Boxes,
        Sigh,
        OpenWindow,
        WindGust,
        NotBirthdaySong,
        CandlesBlow,
        OpenShopDoor,
        LampToggle,
        BedtimeYawn,
        DeepSigh,
        DriveByCar,
        LockedDoor,
        KnockOnDoor,
        WakeupAlarm,
        SnoringSounds,
        SmashingGlass,
        BusApproach,
        BusDoorOpen,
        BusDriveAway,
        UncannyLecture,
        AudienceLaughter,
        SchoolBell,
        AirHorn,
        StacyTypewriterSound,
        KabowskiTypewriterSound,
        NikolaiTypewriterSound,
        BrainTypewriterSound,
        Sobbing,
        DadTypewriterSound,
        MomTypewriterSound,
        BloomerTypewriterSound,
        DoomerGirlTypewriterSound,
        PepeTypewriterSound,
        DoomerTypewriterSound,
        SoyRedditTypewriterSound,
        SoyDiscordTypewriterSound,
        CoomerTypewriterSound,
        BoomerTypewriterSound,
        RobotWalk,
        VoiceTypewriterSound,
        Crickets,
        Prayer,
        TimeTicking,
        BoomerLaugh,
        TenHoursLater,
        DiscordSound,
        DiscordCall,
        DiscordLeave,
        DiscordNotifSpam,
        PhoneRing,
        RobotWorkout,
        Reeee,
        BlueScreen,
        ZoomerTypewriterSound,
        EatingFood,
        CookingFood,
        SuccessSound,
        FailSound,
        CrunchyBite,
        Microwave,
        BeerOpen,
        EatingCarrots,
        LickIceCream,
        OpenFridgeDoor,
        ThrowAwayTrash,
        GamingSounds,
        CodingSounds,
        WatchingVideos,
        TurnOnPC,
        Kiss,
        KabowskiSex,
        ReaperTypewriter,
        KidTypewriter,
        PlayerTypewriterYoung,
        DoctorTypewriter,
        DyingRobotTypewriter,
        OldRobotTypewriter,
        TeenRobotTypewriter,
        ChildRobotTypewriter, // oops made two, this isnt being used. Use PlayerTyperwriterYoung instead
        BrotherTypewriter,
        NerdFriendTypewriter,
        ArriveHome,
        LittleBoyTypewriterSound,
        LittleGirlTypewriterSound,
        ChewPizza,
        TextingPhone,
        TrashDumpster,
        ManCry,
        TypingSounds,
        StandingHere,
        Sniff,
        Applause,
        OvenBeep,
        VoiceDying,
        VoiceDying2,
        SlackNotif,
        OlderRobotTypewriter,
        OlderFriendTypewriter,
        BossTypewriter,
        WalkieTalkie,
        OlderBrotherTypewriter,
        NurseTypewriterSound,
        PatOnTheBack,
        ChairPushBack,
        HandOverBox,
        LightApplause,
        Hug,
        GameTypewriter,
        SelectSound1,
        SelectSound2,
        AutumnWalk,
        Running,
        BrushTeeth,
        MicrowaveAndEat,
        TakeShit,
        EvilLaugh,

        LowBattery,
    }

    public SoundName soundName;
    public AudioClip[] soundClips;
    public string soundDescription;
    [Range(0.1f, 1.5f)]
    public float soundPitchRandomVariationMin = 0.8f;
    [Range(0.1f, 1.5f)]
    public float soundPitchRandomVariationMax = 1.2f;
    [Range(0f, 1f)]
    public float soundVolume = 1f;
}
